### ISSUE TITLE
Sent offers being lost

### ISSUE THREAD

**Issue by mikehhhhhhh** [steam-forward/node-steam-forum#67] opened 2015-08-16 17:13 UTC
Has anyone else had an issue where sent offers are being lost?

The sent offer seems to be confirmed but never arrives at the other end.

If so, have any of you managed to work around it?

**Comment by scholtzm** [comment] 2015-08-16 17:59
Possible duplicate of https://github.com/steam-forward/node-steam-forum/issues/50

**Closed** 2015-09-26 11:50 UTC
